= Classes

== Top-level type footnote:[OCP 17 / 1Z0-829, p. 7.]
A _top-level type_ is a data structure that can be defined independently within a source file.

Can be `public` or `default (package-private)` by access modifiers.

Classes of access modifier `package-private` can be accessed only from within their package.

You can even put two types in the same file. When you do so, *at most one (!!!)* of the top-level types in the file is allowed to be `public`.

It doesn't matter, whether classes contain `main` method - they will be compiled successfully if filename is equal to public top-level class' name.

.Example
[source, java]
public class Animal {
    private String name;
}
class Animal2 {}

If you do have a public type, it needs to match the filename. The declaration `public class Animal2` would not compile in a file named `Animal.java`.

.Examples
* [blue]#*GOOD*# +
  *FILENAME:* `Animal.java` +
  *javac Animal.java PRODUCES:* +
  `Animal.class` +
  `Animal2.class`
[source, java]
public class Animal {
    private String name;
}
class Animal2 {}

* [blue]#*GOOD*# +
*FILENAME:* `Animal.java` (or any random name) +
*javac Animal.java PRODUCES:* +
`Animal2.class` +
`Animal3.class`
[source, java]
class Animal2 {}
class Animal3 {}

* [red]#*BAD*# +
*FILENAME:* `Animal2.java` +
*javac Animal2.java PRODUCES:* +
error: class Animal is public, should be declared in a file named Animal.java
[source, java]
public class Animal {
    private String name;
}
class Animal2 {}

* [red]#*BAD*# +
*FILENAME:* `Animal2.java` +
*javac Animal2.java PRODUCES:* +
error: class Animal is public, should be declared in a file named Animal.java
[source, java]
public class Animal {
    private String name;
}
public class Animal2 {}

TIP: See link:../src/by/olegyev/ocp17/classes/TopLevelType.java[source code].

TIP: A possible reason why public top-level class' name should be equal to filename is within `import` statement (or fully-qualified class name's using). Package-private classes can be instantiated and called only within the same package, where `import` statement is redundant for them (though possible - see source code from the tip above). However, it is possible to use `public` classes outside their packages, which requires explicit `import` statement or fully-qualified class name. For compiler, it is quicker to traverse through the classpath and find necessary class for import by filename. For package-private classes, in turn, it is ok to have different filename, becuase it is considered easier to traverse through the .java files within the same package. +
*NB!* If we are compiling some Main class with the dependencies using, for instance, `javac -sourcepath .. Main.java`, it will automatically compile all its dependencies as well.